---
output:
  pdf_document:
    keep_tex:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}

library(tidyverse)
library(HDInterval)
library(truncnorm)

M_val <- function(d13C, d13C_sd, 
                  # d13C_otolith value and SD
                  Year, 
                  # Year of capture
                  reps, 
                  # Number of repetitions when sampling from distributions
                  DIC_surf, DIC_surf_sd, 
                  # d13C_DIC value and SD from capture location
                  DIC_min, DIC_max, 
                  # Global d13C_DIC min and max
                  suess, suess_sd, 
                  # Post-1970 Suess effect and SD from capture location
                  suess_min, suess_max, 
                  # Global Suess effect min and max
                  suess_1970, suess_1970_sd, 
                  # Pre-1970 Suess effect and SD
                  phyto, phyto_sd, 
                  # d13C_phyto and SD from capture location
                  phyto_min, phyto_max, 
                  # Global d13C_phyto min and max
                  phyto_suess, phyto_suess_sd, 
                  # Suess effect for phytoplankton and SD
                  troph, troph_se,
                  # Trophic level and SE
                  troph_min, troph_max, 
                  # Min and max trophic level for fishes
                  enrich, enrich_se, 
                  # Trophic enrichment of d13C and SD
                  e_value){ # e (fractiontion) term
  
  # Calculate distributions of component values with set.seeds to ensure reproducibility
  set.seed(d13C)
  dist_d13C <- rnorm(reps, d13C, d13C_sd)
  set.seed(DIC_surf)
  dist_DIC_surf <- rtruncnorm(reps, DIC_min, DIC_max, DIC_surf, DIC_surf_sd)
  set.seed(suess)
  dist_suess <- rtruncnorm(reps, suess_min, suess_max, suess, suess_sd)
  set.seed(suess_1970)
  dist_suess_1970 <- rtruncnorm(reps, suess_min, suess_max, suess_1970, suess_1970_sd)
  set.seed(phyto)
  dist_phyto <- rtruncnorm(reps, phyto_min, phyto_max, phyto, phyto_sd)
  set.seed(phyto_suess)
  dist_phyto_suess <- rtruncnorm(reps, suess_min, suess_max, phyto_suess, phyto_suess_sd)
  set.seed(troph)
  dist_troph <- rtruncnorm(reps, troph_min, troph_max, troph, troph_se)
  set.seed(enrich)
  dist_enrich <- rnorm(reps, enrich, enrich_se)
  set.seed(Sys.time())
  
  # Calculate d13C_DIC, correcting for the Suess effect
  dist_DIC <- if(Year < 1970){
    dist_DIC_surf-(dist_suess_1970*((1990-Year)/10))
  } else if(Year < 1990){
    dist_DIC_surf-(dist_suess*((1990-Year)/10))
  } else {
    dist_DIC_surf+(dist_suess*((1990-Year)/10))
  }
  
  # Calculate d13C_Phyto, correcting for the Suess effect
  dist_phyto_corr <- if(Year < 1970){
    dist_phyto-(dist_phyto_suess*((2001-Year)/10))
  } else if(Year < 2001){
    dist_phyto-(dist_phyto_suess*((2001-Year)/10))
  } else if(Year > 2010){
    dist_phyto+(dist_phyto_suess*((2010-Year)/10))
  } else {
    dist_phyto
  }
  
  # Calculate d13C_diet
  dist_diet <- dist_phyto_corr + (dist_troph - 1) * dist_enrich
  
  # Calculate M
  dist_M <- (dist_d13C - dist_DIC) / (dist_diet - dist_DIC) + e_value
  
  # Get maximum density value for M
  max_dens <- which.max(density(dist_M)$y)
  M <- density(dist_M)$x[max_dens]
  
  # Get minimum, maximum and sd for M distribution
  min_M <- min(dist_M)
  max_M <- max(dist_M)
  sd_M <- sd(dist_M)
  
  # Combine results
  result <- data.frame(M, sd_M, min_M, max_M)
  return(result)
}

```

```{r}

# Read in data

setwd("~/PhD/GitHub/mytophid-ears")
load("Functions/M_Val.Rdata")
myct <- read.csv("Data/Myctophids_Master.csv")

with(myct[2,], # Fish number two in master data set
     M_Val(d13C, 0.02, 
           # SD from isotope lab
           Year.x, 10000,
           DIC, 0.202, 0, 3, 
           # From Tagliabue & Bopp, 2007
           Suess, 0.202, -0.28, 0, 
           # From Tagliabue & Bopp, 2007. SD same as for DIC
           -0.07, 0.202, 
           # From Tagliabue & Bopp, 2007. SD same as for DIC
           Phyto, Phyto_sd, -31, -16.5, 
           # From Magozzi et al. 2017. Based on values for Longhurst provinces
           -0.17, 0.202, 
           # From Clive - per comms. SD same as for DIC
           UseTroph, UseTrophSe, 2, 5, 
           # From FishBase
           0.8, 1.1, 
           # From DeNiro & Epstein 1978
           0)) # From Solomon et al. 2006
```

* M = value at maximum density of distribution of M values.
* sd_M = standard deviation of M distribution.
* min_M = minimum value of M distribution.
* max_M = maximum value of M distribution.