---
output:
  pdf_document:
    keep_tex:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}

library(tidyverse)
library(HDInterval)
library(truncnorm)

Temp_Vals <- function(d18O, d18O_sd, 
                             # d18O_otolith values and SD
                             d18O_water, d18O_water_sd, 
                             # d18O_SW values and SD
                             d18O_water_min, d18O_water_max, 
                             # Global min and max for d18O_SW
                             reps){ 
                             # Number of repetitions when sampling from distributions
  
  # Calculate distributions of component values with set.seeds to ensure reproducibility
  set.seed(d18O)
  dist_d18O <- rnorm(reps, d18O, d18O_sd)
  set.seed(d18O_water)
  dist_d18O_water <- rtruncnorm(reps, d18O_water_min, d18O_water_max, d18O_water, 
                                d18O_water_sd)
  # Set parameter values from Hoie et al. 2004
  set.seed(3.9)
  dist_param_1 <- rnorm(reps, 3.90, 0.24)
  set.seed(-0.20)
  dist_param_2 <- rnorm(reps, -0.20, 0.019)
  
  # Calculate temperature
  dist_d18 <- dist_d18O - dist_d18O_water
  dist_temp <- (dist_d18 - dist_param_1)/dist_param_2
  
  # Get maximum density of temperature
  max_dens <- which.max(density(dist_temp)$y)
  temp <- density(dist_temp)$x[max_dens]
  
  # Get minimum, maximum and sd of temperature
  min_temp <- min(dist_temp)
  max_temp <- max(dist_temp)
  sd_temp <- sd(dist_temp)
  
  # Return results
  result <- data.frame(temp, sd_temp, min_temp, max_temp)
  return(result)
}
```

```{r}

# Read in and tidy data
setwd("~/PhD/GitHub/mytophid-ears")
myct <- read.csv("Data/Myctophids_Master.csv")
myct <- filter(myct, d13C != "NA")
d18O_sd <- sd(myct$D18O_vals)
d18O_min <- min(myct$D18O_vals)
d18O_max <- max(myct$D18O_vals)

with(myct[3,], # Fish number three in master data set
     Temp_Vals(d18O, 0.02, # SD from isotope data
                      D18O_vals, d18O_sd, # SD from data
                      d18O_min, d18O_max, # Min-max from data
                      10000))

```

* temp = value at maximum density of distribution of temperature values.
* sd_temp = standard deviation of temperature distribution.
* min_temp = minimum value of temperature distribution.
* max_temp = maximum value of temperature distribution.